### ISSUE TITLE
Revisit tests involving source interface propagation

### ISSUE THREAD

**Issue by PurelyApplied** [google/go-flow-levee#279]
## Bug report

**Describe the bug**
While iterating #278, I noticed that `internal/pkg/config/testdata/test-config.yaml` will pass all tests with the following Source specification removed:

```yaml
Sources:
  # ...
  - Package: "levee_analysistest/example/core"
    Type: "SourceManipulator"
```

This was introduced in #264.

**To Reproduce**
Remove or comment out the above configuration.  Observe that tests pass.  See #278 first test run for demonstration.
